import key from '@/database/key'
const WRITTEN_TO_LATIN: { [index: string]: { traditional: string[]; latin: string[]; cyrillic: string[] } } = {
  [key.a]: { traditional: [key.a], latin: ['a'], cyrillic: ['а'] },
  [key.b]: { traditional: [key.b], latin: ['b'], cyrillic: ['б'] },
  [key.ch]: { traditional: [key.ch], latin: ['ch', 'ts'], cyrillic: ['ч', 'ц'] },
  [key.d]: { traditional: [key.d], latin: ['d'], cyrillic: ['д'] },
  [key.e]: { traditional: [key.e], latin: ['e'], cyrillic: ['э'] },
  [key.f]: { traditional: [key.f], latin: ['f'], cyrillic: ['ф'] },
  [key.g]: { traditional: [key.g], latin: ['g'], cyrillic: ['г'] },
  [key.h]: { traditional: [key.h], latin: ['h'], cyrillic: ['х'] },
  [key.i]: { traditional: [key.i], latin: ['i'], cyrillic: ['и'] /* ['и', 'й', 'ы', 'ъ', 'ь'] */ },
  [key.j]: { traditional: [key.j], latin: ['j'], cyrillic: ['ж', 'з'] },
  [key.k]: { traditional: [key.k], latin: ['k'], cyrillic: ['к'] },
  [key.l]: { traditional: [key.l], latin: ['l'], cyrillic: ['л'] },
  [key.m]: { traditional: [key.m], latin: ['m'], cyrillic: ['м'] },
  [key.n]: { traditional: [key.n], latin: ['n'], cyrillic: ['н'] },
  [key.o]: { traditional: [key.o, key.ou], latin: ['o', 'u'], cyrillic: ['о'] },
  [key.ou]: { traditional: [key.ou, key.uo], latin: ['o', 'u'], cyrillic: ['у'] },
  [key.p]: { traditional: [key.p], latin: ['p'], cyrillic: ['п'] },
  [key.r]: { traditional: [key.r], latin: ['r'], cyrillic: ['р'] },
  [key.s]: { traditional: [key.s], latin: ['s'], cyrillic: ['с'] },
  [key.t]: { traditional: [key.t], latin: ['t'], cyrillic: ['т'] },
  [key.u]: { traditional: [key.u, key.uo], latin: ['u'], cyrillic: ['у'] },
  [key.uo]: { traditional: [key.uo, key.u], latin: ['o', 'u'], cyrillic: ['ү'] },
  [key.v]: { traditional: [key.v], latin: ['v'], cyrillic: ['в'] },
  [key.sh]: { traditional: [key.sh], latin: ['sh'], cyrillic: ['ш'] },
  [key.y]: { traditional: [key.y], latin: ['y'], cyrillic: ['я', 'ю', 'е', 'ё'] },
  [key.z]: { traditional: [key.z], latin: ['z'], cyrillic: ['з'] },
  [key.empty]: { traditional: [key.empty], latin: [''], cyrillic: [''] },
  [key.connectorWithNoEmptySpace]: { traditional: [key.connectorWithNoEmptySpace], latin: [''], cyrillic: [''] },
  [key.ts]: { traditional: [key.ts], latin: ['ts'], cyrillic: ['ц'] },
  [key.lh]: { traditional: [key.lh], latin: ['lh'], cyrillic: ['лх'] },
  [key.ng]: { traditional: [key.ng], latin: ['n'], cyrillic: ['н'] },
}

export default WRITTEN_TO_LATIN
